# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: query

git:
  ignore_tags:
    - docs

release:
  header: |
    Get the latest release with brew or binary:

    ```sh
    # curl -fSL https://github.com/rytsh/query/releases/latest/download/query_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ query
    curl -fSL https://github.com/rytsh/query/releases/download/{{ .Tag }}/query_Linux_x86_64.tar.gz | tar -xz --overwrite -C ~/bin/ query
    ```
  footer: |
    **Full Changelog**: https://github.com/rytsh/query/compare/{{ .PreviousTag }}...{{ .Tag }}
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64
    main: ./cmd/query
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - 'merge conflict'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

brews:
- name: query
  homepage: https://github.com/rytsh/query
  description: "db query command line tool"
  repository:
    owner: brew-tools
    name: homebrew-tap
    token: "{{ .Env.BREW_TOKEN }}"
  directory: Formula

dockers:
- image_templates:
  - 'ghcr.io/rytsh/query:{{ .Tag }}'
  - 'ghcr.io/rytsh/query:latest'
  dockerfile: ci/Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=io.artifacthub.package.readme-url=https://raw.githubusercontent.com/rytsh/query/main/README.md"
  - "--label=io.artifacthub.package.maintainers=[{\"name\":\"Eray Ates\",\"email\":\"eates23@gmail.com\"}]"
  - "--label=io.artifacthub.package.license=MIT"
  - "--label=org.opencontainers.image.description=db query command line tool"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source={{.GitURL}}"
  - "--build-arg=DB_IMAGE=ghcr.io/rytsh/dock/db/multi:debian-12.6-slim"
  - "--build-arg=GO_IMAGE=ghcr.io/rytsh/dock/build/go:1.23.0"
